general.import = [
	"~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 25
decorations = "transparent"

opacity = 0.9
blur = true

title = "Better than All"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
